[versions]
kotlinTarget = "2.3"
javaTarget = "17"

kotlin = "2.3.10"
asm = "9.9.1"

xemanticKotlinTest = "1.17.3"

versionsPlugin = "0.53.0"
dokkaPlugin = "2.1.0"
mavenPublishPlugin = "0.36.0"
jreleaserPlugin = "1.22.0"
xemanticConventionsPlugin = "0.6.8"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
xemantic-kotlin-test = { module = "com.xemantic.kotlin:xemantic-kotlin-test", version.ref = "xemanticKotlinTest" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaserPlugin" }
xemantic-conventions = { id = "com.xemantic.gradle.xemantic-conventions", version.ref = "xemanticConventionsPlugin" }
